# Generated by Django 2.2.28 on 2023-06-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_desc',
            new_name='task_description',
        ),
    ]
